apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.app.servicePort }}
      targetPort: {{ .Values.app.containerPort }}

